/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Perro;

import Agenda.DatosFactura;
import Agenda.Factura;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class Reporte extends javax.swing.JFrame {

    private Perro dog;
    private Factura f;

    /**
     * Creates new form Reporte
     */
    public Reporte() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        dog = new Perro();
        f = new Factura();
        DatosCliente datosC = new DatosCliente();

        datosC.ConteoGenero(dog);
        datosC.ConteoTamaño(dog);
        DatosFactura datosf = new DatosFactura();

        datosf.ConteoGrooming(f);
        datosf.ConteoDog(f);
        datosf.ConteoGanancias(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenerarRepote = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnReporteEmpresa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        btnGenerarRepote.setBackground(new java.awt.Color(153, 204, 255));
        btnGenerarRepote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerarRepote.setText("Reportes clientes");
        btnGenerarRepote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarRepoteActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.png"))); // NOI18N
        jLabel15.setText("HOTEL ROOF");

        btnReporteEmpresa.setBackground(new java.awt.Color(153, 204, 255));
        btnReporteEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReporteEmpresa.setText("Reportes empresa");
        btnReporteEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReporteEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarRepote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(39, 39, 39)
                .addComponent(btnGenerarRepote)
                .addGap(48, 48, 48)
                .addComponent(btnReporteEmpresa)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarRepoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRepoteActionPerformed

        JOptionPane.showMessageDialog(null, dog.verEstadistica(), "Reporte ", JOptionPane.PLAIN_MESSAGE,
                new ImageIcon("src/img/logo.png"));
    }//GEN-LAST:event_btnGenerarRepoteActionPerformed

    private void btnReporteEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteEmpresaActionPerformed

        JOptionPane.showMessageDialog(null, f.verEstadistica(), "Reporte ", JOptionPane.PLAIN_MESSAGE,
                new ImageIcon("src/img/logo.png"));
    }//GEN-LAST:event_btnReporteEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarRepote;
    private javax.swing.JButton btnReporteEmpresa;
    private javax.swing.JLabel jLabel15;
    // End of variables declaration//GEN-END:variables

}
