/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tienda;

import javax.swing.JOptionPane;

/**
 *
 * @author indir
 */
public class JFMProductos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    public JFMProductos() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bntRestar = new javax.swing.JButton();
        bntSumar = new javax.swing.JButton();
        txtCantidad1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        bntRestar1 = new javax.swing.JButton();
        bntSumar1 = new javax.swing.JButton();
        txtCantidad2 = new javax.swing.JTextField();
        bntRestar2 = new javax.swing.JButton();
        bntSumar2 = new javax.swing.JButton();
        txtCantidad3 = new javax.swing.JTextField();
        bntRestar3 = new javax.swing.JButton();
        bntSumar3 = new javax.swing.JButton();
        txtCantidad4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtJuguetes = new javax.swing.JTextField();
        txtMontoG = new javax.swing.JTextField();
        txtMontoC = new javax.swing.JTextField();
        txtMontoJ2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 620));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/correa-de-perro (4).png"))); // NOI18N
        jLabel3.setText("Correa");

        bntRestar.setText("-");
        bntRestar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntRestarMouseClicked(evt);
            }
        });
        bntRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRestarActionPerformed(evt);
            }
        });

        bntSumar.setText("+");
        bntSumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntSumarMouseClicked(evt);
            }
        });
        bntSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSumarActionPerformed(evt);
            }
        });

        txtCantidad1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad1.setText("0");
        txtCantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aseo (2).png"))); // NOI18N
        jLabel7.setText("Kit Grooming");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/juguete (1).png"))); // NOI18N
        jLabel8.setText("Kit Juguetes 1");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/juguetes (1).png"))); // NOI18N
        jLabel10.setText("Kit juguetes 2");

        btnPagar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carro-de-la-carretilla (1).png"))); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        bntRestar1.setText("-");
        bntRestar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntRestar1MouseClicked(evt);
            }
        });
        bntRestar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRestar1ActionPerformed(evt);
            }
        });

        bntSumar1.setText("+");
        bntSumar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntSumar1MouseClicked(evt);
            }
        });
        bntSumar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSumar1ActionPerformed(evt);
            }
        });

        txtCantidad2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad2.setText("0");
        txtCantidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad2ActionPerformed(evt);
            }
        });

        bntRestar2.setText("-");
        bntRestar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntRestar2MouseClicked(evt);
            }
        });
        bntRestar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRestar2ActionPerformed(evt);
            }
        });

        bntSumar2.setText("+");
        bntSumar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntSumar2MouseClicked(evt);
            }
        });
        bntSumar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSumar2ActionPerformed(evt);
            }
        });

        txtCantidad3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad3.setText("0");
        txtCantidad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad3ActionPerformed(evt);
            }
        });

        bntRestar3.setText("-");
        bntRestar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntRestar3MouseClicked(evt);
            }
        });
        bntRestar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRestar3ActionPerformed(evt);
            }
        });

        bntSumar3.setText("+");
        bntSumar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntSumar3MouseClicked(evt);
            }
        });
        bntSumar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSumar3ActionPerformed(evt);
            }
        });

        txtCantidad4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad4.setText("0");
        txtCantidad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tienda Roof");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Kit Juguetes 1");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Kit Grooming");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Kit juguetes 2");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Correa");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Monto:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Monto:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Monto:");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Monto:");

        txtJuguetes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJuguetes.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtJuguetes.setEnabled(false);

        txtMontoG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMontoG.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtMontoG.setEnabled(false);

        txtMontoC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMontoC.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtMontoC.setEnabled(false);

        txtMontoJ2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMontoJ2.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtMontoJ2.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Subtotal:");

        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtTotal.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("IVA: ");

        txtIVA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIVA.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtIVA.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Monto a pagar: ");

        txtMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMonto.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtMonto.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMontoC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal)
                            .addComponent(txtIVA)
                            .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(52, 52, 52))
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtJuguetes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMontoG, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMontoJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJuguetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtMontoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMontoG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMontoJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(164, 164, 164))))
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-contacto.png"))); // NOI18N
        jButton1.setText("Crear Factura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(bntSumar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bntRestar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bntSumar2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bntRestar2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bntSumar1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bntRestar1))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bntSumar3)))
                                .addGap(12, 12, 12)
                                .addComponent(txtCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntRestar3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPagar)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bntSumar)
                                    .addComponent(bntRestar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntSumar1)
                            .addComponent(txtCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntRestar1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(bntSumar2)
                            .addComponent(txtCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntRestar2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(bntSumar3)
                            .addComponent(txtCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntRestar3))
                        .addGap(65, 65, 65)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(btnPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRestarActionPerformed

    }//GEN-LAST:event_bntRestarActionPerformed

    private void bntSumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntSumarMouseClicked
        int cantidad = 0;

        try {
            cantidad = Integer.parseInt(txtCantidad1.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        if (cantidad < 10) {
            cantidad++;
            txtCantidad1.setText(String.valueOf(cantidad));
        } else {
            JOptionPane.showMessageDialog(null, "El maximo de este ariculo por cliente es 10 ");
        }
    }//GEN-LAST:event_bntSumarMouseClicked

    private void txtCantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad1ActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        JOptionPane.showMessageDialog(null, "Factura Creada");
        ////////-----------------------------------------------------------------------------------
        JOptionPane.showMessageDialog(null, "\n\nFACTURA"
                + "\nKit Juguetes 1: " + txtCantidad1.getText()
                + "\nKit Grooming: " + txtCantidad2.getText()
                + "\nCorrrea: " + txtCantidad3.getText()
                + "\nKit Juguetes 2: " + txtCantidad4.getText());

    }//GEN-LAST:event_btnPagarActionPerformed

    private void bntSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSumarActionPerformed

    }//GEN-LAST:event_bntSumarActionPerformed

    private void bntRestarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRestarMouseClicked
        int cantidad = 0;

        try {
            cantidad = Integer.parseInt(txtCantidad1.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        if (cantidad > 0) {
            cantidad--;
            txtCantidad1.setText(String.valueOf(cantidad));
        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_bntRestarMouseClicked

    private void bntRestar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRestar1MouseClicked
        int cantidad2 = 0;

        try {
            cantidad2 = Integer.parseInt(txtCantidad2.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        if (cantidad2 > 0) {
            cantidad2--;
            txtCantidad2.setText(String.valueOf(cantidad2));
        } else {
            JOptionPane.showMessageDialog(null, "Error: ");
        }
    }//GEN-LAST:event_bntRestar1MouseClicked

    private void bntRestar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRestar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntRestar1ActionPerformed

    private void bntSumar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntSumar1MouseClicked
        int cantidad2 = 0;

        try {
            cantidad2 = Integer.parseInt(txtCantidad2.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        if (cantidad2 < 10) {
            cantidad2++;
            txtCantidad2.setText(String.valueOf(cantidad2));
        } else {
            JOptionPane.showMessageDialog(null, "El maximo de este ariculo por cliente es 10 ");
        }
    }//GEN-LAST:event_bntSumar1MouseClicked

    private void bntSumar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSumar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntSumar1ActionPerformed

    private void txtCantidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad2ActionPerformed

    private void bntRestar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRestar2MouseClicked
        int cantidad3 = 0;

        try {
            cantidad3 = Integer.parseInt(txtCantidad3.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        if (cantidad3 > 0) {
            cantidad3--;
            txtCantidad3.setText(String.valueOf(cantidad3));
        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_bntRestar2MouseClicked

    private void bntRestar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRestar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntRestar2ActionPerformed

    private void bntSumar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntSumar2MouseClicked
        int cantidad3 = 0;

        try {
            cantidad3 = Integer.parseInt(txtCantidad3.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        if (cantidad3 < 10) {
            cantidad3++;
            txtCantidad3.setText(String.valueOf(cantidad3));
        } else {
            JOptionPane.showMessageDialog(null, "El maximo de este ariculo por cliente es 10 ");
        }
    }//GEN-LAST:event_bntSumar2MouseClicked

    private void bntSumar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSumar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntSumar2ActionPerformed

    private void txtCantidad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad3ActionPerformed

    private void bntRestar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRestar3MouseClicked
        int cantidad4 = 0;

        try {
            cantidad4 = Integer.parseInt(txtCantidad4.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        if (cantidad4 > 0) {
            cantidad4--;
            txtCantidad4.setText(String.valueOf(cantidad4));
        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_bntRestar3MouseClicked

    private void bntRestar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRestar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntRestar3ActionPerformed

    private void bntSumar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntSumar3MouseClicked
        int cantidad4 = 0;

        try {
            cantidad4 = Integer.parseInt(txtCantidad4.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        if (cantidad4 < 10) {
            cantidad4++;
            txtCantidad4.setText(String.valueOf(cantidad4));
        } else {
            JOptionPane.showMessageDialog(null, "El maximo de este ariculo por cliente es 10 ");
        }
    }//GEN-LAST:event_bntSumar3MouseClicked

    private void bntSumar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSumar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntSumar3ActionPerformed

    private void txtCantidad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calcularKitJuguetes();
        calcularKitGrooming();
        calcularCorrea();
        calcularKitJuguetes2();
        calcularMon();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void calcularKitJuguetes() {
        int cantidadKit1 = Integer.parseInt(txtCantidad1.getText());
        int precioKit = 2500;
        int totalkit = cantidadKit1 * precioKit;
        txtCantidad1.setText(String.valueOf(totalkit));
        txtJuguetes.setText(String.valueOf(totalkit));
    }

    private void calcularKitGrooming() {
        int cantidadKitGrooming = Integer.parseInt(txtCantidad2.getText());
        int precioKit = 2500;
        int totalkitG = cantidadKitGrooming * precioKit;

        txtCantidad2.setText(String.valueOf(totalkitG));
        txtMontoG.setText(String.valueOf(totalkitG));
    }

    private void calcularCorrea() {
        int cantidadCorrea = Integer.parseInt(txtCantidad3.getText());
        int precio = 5000;
        int total = cantidadCorrea * precio;
        txtCantidad3.setText(String.valueOf(total));
        txtMontoC.setText(String.valueOf(total));
    }

    private void calcularKitJuguetes2() {
        int cantidadKit2 = Integer.parseInt(txtCantidad4.getText());
        int precioKit2 = 2500;
        int totalkit2 = cantidadKit2 * precioKit2;
        txtCantidad4.setText(String.valueOf(totalkit2));
        txtMontoJ2.setText(String.valueOf(totalkit2));
    }

    private void calcularMon() {
        int mont1 = Integer.parseInt(txtJuguetes.getText());
        int mont2 = Integer.parseInt(txtMontoG.getText());
        int mont3 = Integer.parseInt(txtMontoC.getText());
        int mont4 = Integer.parseInt(txtMontoJ2.getText());
        int total = mont1 + mont2 + mont3 + mont4;
        txtTotal.setText(String.valueOf(total));
        double iva = total * 0.13;
        txtIVA.setText(String.valueOf(iva));
        double pagar = (total + iva);
        txtMonto.setText(String.valueOf(pagar));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntRestar;
    private javax.swing.JButton bntRestar1;
    private javax.swing.JButton bntRestar2;
    private javax.swing.JButton bntRestar3;
    private javax.swing.JButton bntSumar;
    private javax.swing.JButton bntSumar1;
    private javax.swing.JButton bntSumar2;
    private javax.swing.JButton bntSumar3;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad1;
    private javax.swing.JTextField txtCantidad2;
    private javax.swing.JTextField txtCantidad3;
    private javax.swing.JTextField txtCantidad4;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtJuguetes;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtMontoC;
    private javax.swing.JTextField txtMontoG;
    private javax.swing.JTextField txtMontoJ2;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
